//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Product_Title { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string Product_Image { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
