//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KajalPatel_01_07_2023Entities : DbContext
    {
        public KajalPatel_01_07_2023Entities()
            : base("name=KajalPatel_01_07_2023Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<StudentDetails> StudentDetails { get; set; }
        public virtual DbSet<StudentMaster> StudentMaster { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Customer1> Customer1 { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
