//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetails
    {
        public int StudentDetailId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string TotalMarks { get; set; }
        public string MarkObtained { get; set; }
        public string Percentage { get; set; }
    
        public virtual StudentMaster StudentMaster { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
